//Projects
export const FETCH_PROJECTS = "FETCH_PROJECTS";

//Sections
export const FETCH_SECTIONS = "FETCH_SECTIONS";
export const DELETE_SECTIONS = "DELETE_SECTIONS";
export const INSERT_SECTIONS = "INSERT_SECTIONS";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";

